### ISSUE TITLE
AIAccessFacet is missing in schema

### ISSUE THREAD

**Issue by boferri** [ubleipzig/intermediateschema#5]
Since it utilised in the span export processing, see https://github.com/miku/span/blob/a05d018c9174fd939cbbd9dacb36f80273ea04dd/formats/finc/solr.go#L171. Since AIAccessFacet is camel-cased, we should think about renaming it, or?

**Comment by miku** [comment]
Yes, the AIAccessFacet value is by default [Electronic Resources](https://github.com/miku/span/blob/a05d018c9174fd939cbbd9dacb36f80273ea04dd/formats/finc/common.go#L33). I would believe that this fixed value should be ok for the moment for most sources.

**Comment by boferri** [comment]
from my current knowledge, this field does not belong to the intermediate schema (right now), it's simply a constant value that is defined in https://github.com/miku/span/blob/master/formats/finc/common.go#L33 and utilised in https://github.com/miku/span/blob/a05d018c9174fd939cbbd9dacb36f80273ea04dd/formats/finc/solr.go#L171
