### ISSUE TITLE
finc.AIRecordType is missing in schema

### ISSUE THREAD

**Issue by boferri** [ubleipzig/intermediateschema#6]
since it is utilised in the span export processing, see https://github.com/miku/span/blob/a05d018c9174fd939cbbd9dacb36f80273ea04dd/formats/finc/solr.go#L98. Since finc.AIRecordType is camel-cased, we should think about renaming it, or? - e.g. finc.record_type

**Comment by miku** [comment]
For siskin/span style processing, the value of AIRecordType is by default [ai](https://github.com/miku/span/blob/a05d018c9174fd939cbbd9dacb36f80273ea04dd/formats/finc/intermediate.go#L34). This is mostly a signal to the VuFind frontend, to use a certain way to access the fullrecord. 

I'm aware of the following record types at the moment:

* ai: use an external blob server
* is: include *intermediate schema* in SOLR [fullrecord](https://github.com/finc/index/blob/e9e7aab477183bb14d33904021c2b61c03913351/schema.xml#L171) field
* marc: include *marc binary* in SOLR [fullrecord](https://github.com/finc/index/blob/e9e7aab477183bb14d33904021c2b61c03913351/schema.xml#L171) field

If you run span-export with `-with-fullrecord` flag, the recordtype is [changed to ](https://github.com/miku/span/blob/e3505a4eacd660d3492b4d337d1933712264064a/formats/finc/solr.go#L95-L99) "is" (and the intermediate schema record is put info the fullrecord field).

**Comment by boferri** [comment]
from my current knowledge, this field does not belong to the intermediate schema (right now), it's simply a constant value that is defined in https://github.com/miku/span/blob/a05d018c9174fd939cbbd9dacb36f80273ea04dd/formats/finc/intermediate.go#L34 and utilised in https://github.com/miku/span/blob/a05d018c9174fd939cbbd9dacb36f80273ea04dd/formats/finc/solr.go#L98
